Replace full fuzzy match with match for lines that begins with link 2

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -49,6 +49,10 @@ jobs:
               echo "Error detected, failing workflow"
               exit 1
             fi
+            if grep -q ' with checkdoc ' output.log ; then
+              echo "Checkdoc warning detected, failing workflow"
+              exit 1
+            fi
           else
             echo "Make command failed, failing workflow"
             exit 1
