configure melpazoid, fix warnings

diff --git a/.github/workflows/melpazoid.yml b/.github/workflows/melpazoid.yml
--- a/.github/workflows/melpazoid.yml
+++ b/.github/workflows/melpazoid.yml
@@ -41,6 +41,10 @@ jobs:
               echo "Warnings detected, failing workflow"
               exit 1
             fi
+            if grep -q ': error: ' output.log ; then
+              echo "Error detected, failing workflow"
+              exit 1
+            fi
           else
             echo "Make command failed, failing workflow"
             exit 1
